services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - fraud-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - fraud-net

  topic-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic transacoes-raw --partitions 3 --replication-factor 1
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic alertas-fraude --partitions 3 --replication-factor 1
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic alertas-fraude-dlq --partitions 1 --replication-factor 1
        echo "Tópicos criados com sucesso"
    networks:
      - fraud-net

  producer:
    build: .
    command: uv run python -m src.producer
    depends_on:
      topic-init:
        condition: service_completed_successfully
    environment:
      PYTHONPATH: /app
      KAFKA_BROKER: kafka:9092
    networks:
      - fraud-net

  flink-processor:
    build: .
    command: uv run python -m src.flink_processor
    depends_on:
      topic-init:
        condition: service_completed_successfully
    environment:
      PYTHONPATH: /app
      KAFKA_BROKER: kafka:9092
      MODEL_PATH: /app/models/fraud_model.joblib
      FLINK_JAR_DIR: /opt/flink/usrlib
      FLINK_PARALLELISM: "3"
      FRAUD_CONFIDENCE_THRESHOLD: "0.7"
    volumes:
      - ./models:/app/models
    networks:
      - fraud-net

  alert-consumer:
    build: .
    command: uv run python -m src.alert_consumer
    depends_on:
      topic-init:
        condition: service_completed_successfully
    environment:
      PYTHONPATH: /app
      KAFKA_BROKER: kafka:9092
    networks:
      - fraud-net

  train-model:
    build: .
    command: uv run python -m src.train_model
    volumes:
      - ./models:/app/models
    environment:
      PYTHONPATH: /app
    networks:
      - fraud-net

networks:
  fraud-net:
    driver: bridge